services:
  shop-online:
    build: ./stats-server/server
    ports:
      - "8084:8084"
    depends_on:
      - shop-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-db:5434/shop
      - SPRING_DATASOURCE_USERNAME=shop
      - SPRING_DATASOURCE_PASSWORD=shop

  shop-db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5434"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - PGUSER=shop
      - POSTGRES_PASSWORD=shop