services:
  online-shop:
    build: ./
    ports:
      - "8084:8084"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shop
      - SPRING_DATASOURCE_USERNAME=shop
      - SPRING_DATASOURCE_PASSWORD=shop

  db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "15434:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - PGUSER=shop
      - POSTGRES_PASSWORD=shop