services:
  shop:
    build: ./shop
    ports:
      - "8084:8084"
    depends_on:
      - db
      - payments-api
      - redis-cache
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/shop
      - SPRING_R2DBC_USERNAME=shop
      - SPRING_R2DBC_PASSWORD=shop
      - SPRING_DATA_R2DBC_REPOSITORIES_ENABLED=true
      - PAYMENTS_SERVER_URL=http://payments-api:8085
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT:6379

  db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "15434:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=shop
      - PGUSER=shop
      - POSTGRES_PASSWORD=shop

  payments-api:
    build: ./payments-api
    ports:
      - "8085:8085"

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"